name = "Snuggle Craft"
author = "SnuggleSMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8779a9c60949e16854480f7f01c7acdc7ddcc2a35607969dcb4e1bda5581b92b"

[versions]
minecraft = "1.21.4"
neoforge = "21.4.156"
